version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.4
  commitlint: conventional-changelog/commitlint@1.0.0
  node: circleci/node@5.0.2
aliases:
  - &save_git_cache
    save_cache:
      paths:
        - .git
      key: v3-git-{{ .Revision }}
  - &restore_git_cache
    restore_cache:
      keys:
        - v3-git-{{ .Revision }}
        - v3-git-
  - &save_build_cache
    save_cache:
      paths:
        - build
      key: v3-build-{{ .Revision }}
  - &restore_build_cache
    restore_cache:
      keys:
        - v3-build-{{ .Revision }}
  - &save_dist_cache
    save_cache:
      paths:
        - dist
      key: v3-dist-{{ .Revision }}
  - &restore_dist_cache
    restore_cache:
      keys:
        - v3-dist-{{ .Revision }}
  - &save_npm_cache
    save_cache:
      paths:
        - node_modules
      key: v3-npm-{{ checksum "package-lock.json" }}
  - &restore_npm_cache
    restore_cache:
      keys:
        - v3-npm-{{ checksum "package-lock.json" }}
        - v3-npm-
  - &defaults
    docker:
      # TODO: fix scratch-audio and change this to `cimg/node:lts-browsers`
      - image: cimg/node:14.20-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    executor: node/default
    working_directory: ~/repo

jobs:
  build-test-no-cache:
    <<: *defaults
    environment:
      DETECT_CHROMEDRIVER_VERSION: "true"
      JEST_JUNIT_OUTPUT_DIR: test-results
      NODE_OPTIONS: --max-old-space-size=4000
    steps:
      - *restore_git_cache
      - checkout
      - browser-tools/install-chrome # must be before node/install-packages
      - node/install-packages
      - run:
          name: Lint
          command: npm run test:lint -- --quiet --output-file test-results/eslint-results.xml --format junit
      - run:
          name: Unit
          environment:
            JEST_JUNIT_OUTPUT_NAME: unit-results.xml
          command: npm run test:unit -- --reporters="default" --reporters="jest-junit" --coverage --coverageReporters=text --coverageReporters=lcov --maxWorkers="2"
      - run:
          name: Build
          environment:
            NODE_ENV: production
          command: npm run build
      - run:
          name: Integration
          environment:
              JEST_JUNIT_OUTPUT_NAME: integration-results.xml
          command: |
              google-chrome --version
              npx --no -- chromedriver --version
              npm run test:integration -- --reporters="default" --reporters="jest-junit"
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: test-results
      - run: npx --no -- semantic-release --dry-run
  setup:
    <<: *defaults
    environment:
      DETECT_CHROMEDRIVER_VERSION: "true"
    steps:
      - *restore_git_cache
      - checkout
      - browser-tools/install-chrome # must be before node/install-packages
      - node/install-packages
      - *save_git_cache
      - *save_npm_cache
  lint:
    <<: *defaults
    steps:
      - *restore_git_cache
      - checkout
      - *restore_npm_cache
      - run:
          name: Lint
          command: npm run test:lint -- --quiet --output-file test-results/eslint/results.xml --format junit
      - store_test_results:
          path: test-results
  unit:
    <<: *defaults
    environment:
      JEST_JUNIT_OUTPUT_NAME: results.xml
    steps:
      - *restore_git_cache
      - checkout
      - *restore_npm_cache
      - run:
          name: Unit
          environment:
              JEST_JUNIT_OUTPUT_DIR: test-results/unit
          command: npm run test:unit -- --reporters="default" --reporters="jest-junit" --coverage --coverageReporters=text --coverageReporters=lcov --maxWorkers="2"
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: test-results
  build:
    <<: *defaults
    environment:
      NODE_ENV: production
      NODE_OPTIONS: --max-old-space-size=4000
    steps:
      - *restore_git_cache
      - checkout
      - *restore_npm_cache
      - run:
          name: Build
          command: npm run build
      - *save_build_cache
      - *save_dist_cache
  store_build:
    <<: *defaults
    steps:
      - *restore_build_cache
      - store_artifacts:
          path: build
  store_dist:
    <<: *defaults
    steps:
      - *restore_dist_cache
      - store_artifacts:
          path: dist
  integration:
    <<: *defaults
    parallelism: 2
    environment:
      JEST_JUNIT_OUTPUT_NAME: results.txt
    steps:
      - *restore_git_cache
      - checkout
      - *restore_npm_cache
      - *restore_build_cache
      - browser-tools/install-chrome
      - run:
          name: Integration
          environment:
              JEST_JUNIT_OUTPUT_DIR: test-results/integration
          command: |
            google-chrome --version
            npx --no -- chromedriver --version
            export TESTFILES=$(circleci tests glob "test/integration/*.test.js" | circleci tests split --split-by=timings)
            $(npm bin)/jest ${TESTFILES} --reporters="default" --reporters="jest-junit" --runInBand
      - store_test_results:
          path: test-results

  deploy-npm:
    <<: *defaults
    steps:
      - *restore_git_cache
      - checkout
      - *restore_npm_cache
      - *restore_dist_cache
      - run:
          name: adjust config for hotfix if necessary
          command: |
            # double brackets are important for matching the wildcard
            if [[ "$CIRCLE_BRANCH" == hotfix/* ]]; then
              sed -e "s|hotfix/REPLACE|${CIRCLE_BRANCH}|" --in-place release.config.js
            fi
      - run: npx --no -- semantic-release

  deploy-gh-pages:
    <<: *defaults
    steps:
      - *restore_git_cache
      - checkout
      - *restore_npm_cache
      - *restore_build_cache
      - run: |
          git config --global user.email $(git log --pretty=format:"%ae" -n1)
          git config --global user.name $(git log --pretty=format:"%an" -n1)
      - run: npm run deploy -- -e $CIRCLE_BRANCH
  push-translations:
    <<: *defaults
    steps:
      - *restore_git_cache
      - checkout
      - *restore_npm_cache
      - run: npm run i18n:src
      - run: npm run i18n:push

workflows:
  version: 2
  commitlint:
    jobs:
      - commitlint/lint:
          target-branch: develop
          filters:
            branches:
              ignore:
                - master
                - develop
                - /^hotfix\/.*/
  push-translations:
    triggers:
      - schedule:
          cron: 0 0 * * * # daily at 12 UTC, 8 ET
          filters:
            branches:
              only:
                - develop
    jobs:
      - setup:
          context:
            - dockerhub-credentials
      - push-translations:
          context:
            - dockerhub-credentials
          requires:
              - setup

  build-test-no-deploy:
    jobs:
      - build-test-no-cache:
          context:
            - dockerhub-credentials
          filters:
            branches:
              ignore:
                - master
                - develop
                - /^hotfix\/.*/
  build-test-deploy:
    jobs:
      - setup:
          context:
            - dockerhub-credentials
          filters:
            branches:
              only:
                - master
                - develop
                - /^hotfix\/.*/
      - lint:
          context:
            - dockerhub-credentials
          requires:
            - setup
      - unit:
          context:
            - dockerhub-credentials
          requires:
            - setup
      - build:
          context:
            - dockerhub-credentials
          requires:
            - setup
      - integration:
          context:
            - dockerhub-credentials
          requires:
            - build
      - store_build:
          context:
            - dockerhub-credentials
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
                - /^hotfix\/.*/
      - store_dist:
          context:
            - dockerhub-credentials
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
                - /^hotfix\/.*/
      - deploy-npm:
          context:
            - dockerhub-credentials
          requires:
            - lint
            - unit
            - integration
            - build
          filters:
            branches:
              only:
                - master
                - develop
                - /^hotfix\/.*/
      - deploy-gh-pages:
          context:
            - dockerhub-credentials
          requires:
            - lint
            - unit
            - integration
            - build
          filters:
            branches:
              ignore:
                - /^dependabot/.*/
                - /^renovate/.*/
                - /^pull/.*/ # don't deploy to  gh pages on PRs.
